<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Models\LG_ITEMS;
use App\Models\LG_PRCLIST;
use App\Models\LG_CLCARD;
use App\Models\LG_PAYLINES;
use App\Models\LG_PAYPLANS;
use App\Models\LG_UNITSETF;
use App\Models\LG_ITMUNITA;
use App\Models\LG_01_CLRNUMS;
use App\Models\LG_01_INVOICE;
use App\Models\LG_SLSCLREL;
use App\Models\LV_01_CLCARD;
use App\Models\LG_01_STLINE;
use App\Imports\ItemDefImport;
use App\Imports\ItemImport;
use Maatwebsite\Excel\Facades\Excel;



class TestController extends Controller
{
    public function test()
    {
        SELECT        LGMAIN.LOGICALREF, LGMAIN.CODE, LGMAIN.DEFINITION_, LGMAIN.CITY, LGMAIN.COUNTRY, LGMAIN.ACTIVE, LGMAIN.CARDTYPE, LGMAIN.SPECODE, LGMAIN.TRADINGGRP, LGMAIN.CYPHCODE, LGMAIN.INCHARGE, 
                         LGMAIN.SPECODE2, LGMAIN.SPECODE3, LGMAIN.SPECODE4, LGMAIN.SPECODE5, LGMAIN.TAXOFFICE, LGMAIN.TAXNR, LGMAIN.TCKNO, LGMAIN.EMAILADDR, LGMAIN.TELNRS1, LGMAIN.TELNRS2, LGMAIN.ORGLOGICREF, 
                         LGMAIN.WFLOWCRDREF, LGMAIN.PURCHBRWS, LGMAIN.SALESBRWS, LGMAIN.FINBRWS, LGMAIN.WFLOWCRD,
                             (SELECT        SUM(B.DEBIT)
                               FROM            LV_888_01_GNTOTCL B
                               WHERE        B.TOTTYP = 1 AND B.CARDREF = LGMAIN.LOGICALREF) AS DEBIT,
                             (SELECT        SUM(B.CREDIT)
                               FROM            LV_888_01_GNTOTCL B
                               WHERE        B.TOTTYP = 1 AND B.CARDREF = LGMAIN.LOGICALREF) AS CREDIT,
                             (SELECT        SUM(B.DEBIT)
                               FROM            LV_888_01_GNTOTCL B
                               WHERE        B.TOTTYP = 2 AND B.CARDREF = LGMAIN.LOGICALREF) AS DEBIT_RD,
                             (SELECT        SUM(B.CREDIT)
                               FROM            LV_888_01_GNTOTCL B
                               WHERE        B.TOTTYP = 2 AND B.CARDREF = LGMAIN.LOGICALREF) AS CREDIT_RD
FROM            LV_888_CLCARD LGMAIN
WHERE        LGMAIN.CARDTYPE NOT IN (4, 22) AND LGMAIN.LOWLEVELCODES1 <> '0'
UNION ALL
SELECT        LGMAIN.LOGICALREF, LGMAIN.CODE, LGMAIN.DEFINITION_, LGMAIN.CITY, LGMAIN.COUNTRY, LGMAIN.ACTIVE, LGMAIN.CARDTYPE, LGMAIN.SPECODE, LGMAIN.TRADINGGRP, LGMAIN.CYPHCODE, LGMAIN.INCHARGE, 
                         LGMAIN.SPECODE2, LGMAIN.SPECODE3, LGMAIN.SPECODE4, LGMAIN.SPECODE5, LGMAIN.TAXOFFICE, LGMAIN.TAXNR, LGMAIN.TCKNO, LGMAIN.EMAILADDR, LGMAIN.TELNRS1, LGMAIN.TELNRS2, LGMAIN.ORGLOGICREF, 
                         LGMAIN.WFLOWCRDREF, LGMAIN.PURCHBRWS, LGMAIN.SALESBRWS, LGMAIN.FINBRWS, LGMAIN.WFLOWCRD,
                             (SELECT        SUM(B.DEBIT)
                               FROM            LV_888_01_GNTOTCL B
                               WHERE        B.TOTTYP = 1 AND B.CARDREF = LGMAIN.LOGICALREF) AS DEBIT,
                             (SELECT        SUM(B.CREDIT)
                               FROM            LV_888_01_GNTOTCL B
                               WHERE        B.TOTTYP = 1 AND B.CARDREF = LGMAIN.LOGICALREF) AS CREDIT,
                             (SELECT        SUM(B.DEBIT)
                               FROM            LV_888_01_GNTOTCL B
                               WHERE        B.TOTTYP = 2 AND B.CARDREF = LGMAIN.LOGICALREF) AS DEBIT_RD,
                             (SELECT        SUM(B.CREDIT)
                               FROM            LV_888_01_GNTOTCL B
                               WHERE        B.TOTTYP = 2 AND B.CARDREF = LGMAIN.LOGICALREF) AS CREDIT_RD
FROM            LV_888_CLCARD LGMAIN
WHERE        LGMAIN.CARDTYPE NOT IN (4, 22) AND LGMAIN.LOWLEVELCODES1 = 0
    }
}



SELECT        LOGICALREF, ACTIVE, CARDTYPE, CODE, DEFINITION_, SPECODE, CYPHCODE, ADDR1, ADDR2, CITY, COUNTRY, POSTCODE, TELNRS1, TELNRS2, FAXNR, TAXNR, TAXOFFICE, INCHARGE, DISCRATE, EXTENREF, 
                         PAYMENTREF, EMAILADDR, WEBADDR, WARNMETHOD, WARNEMAILADDR, WARNFAXNR, CLANGUAGE, VATNR, BLOCKED, BANKBRANCHS1, BANKBRANCHS2, BANKBRANCHS3, BANKBRANCHS4, BANKBRANCHS5, 
                         BANKBRANCHS6, BANKBRANCHS7, BANKACCOUNTS1, BANKACCOUNTS2, BANKACCOUNTS3, BANKACCOUNTS4, BANKACCOUNTS5, BANKACCOUNTS6, BANKACCOUNTS7, DELIVERYMETHOD, DELIVERYFIRM, CCURRENCY, 
                         TEXTINC, SITEID, RECSTATUS, ORGLOGICREF, EDINO, TRADINGGRP, CAPIBLOCK_CREATEDBY, CAPIBLOCK_CREADEDDATE, CAPIBLOCK_CREATEDHOUR, CAPIBLOCK_CREATEDMIN, CAPIBLOCK_CREATEDSEC, 
                         CAPIBLOCK_MODIFIEDBY, CAPIBLOCK_MODIFIEDDATE, CAPIBLOCK_MODIFIEDHOUR, CAPIBLOCK_MODIFIEDMIN, CAPIBLOCK_MODIFIEDSEC, PAYMENTPROC, CRATEDIFFPROC, WFSTATUS, PPGROUPCODE, PPGROUPREF, 
                         TAXOFFCODE, TOWNCODE, TOWN, DISTRICTCODE, DISTRICT, CITYCODE, COUNTRYCODE, ORDSENDMETHOD, ORDSENDEMAILADDR, ORDSENDFAXNR, DSPSENDMETHOD, DSPSENDEMAILADDR, DSPSENDFAXNR, 
                         INVSENDMETHOD, INVSENDEMAILADDR, INVSENDFAXNR, SUBSCRIBERSTAT, SUBSCRIBEREXT, AUTOPAIDBANK, PAYMENTTYPE, LASTSENDREMLEV, EXTACCESSFLAGS, ORDSENDFORMAT, DSPSENDFORMAT, 
                         INVSENDFORMAT, REMSENDFORMAT, STORECREDITCARDNO, CLORDFREQ, ORDDAY, LOGOID, LIDCONFIRMED, EXPREGNO, EXPDOCNO, EXPBUSTYPREF, INVPRINTCNT, PIECEORDINFLICT, COLLECTINVOICING, 
                         EBUSDATASENDTYPE, INISTATUSFLAGS, SLSORDERSTATUS, SLSORDERPRICE, LTRSENDMETHOD, LTRSENDEMAILADDR, LTRSENDFAXNR, LTRSENDFORMAT, IMAGEINC, CELLPHONE, SAMEITEMCODEUSE, STATECODE, 
                         STATENAME, WFLOWCRDREF, PARENTCLREF, LOWLEVELCODES1, LOWLEVELCODES2, LOWLEVELCODES3, LOWLEVELCODES4, LOWLEVELCODES5, LOWLEVELCODES6, LOWLEVELCODES7, LOWLEVELCODES8, 
                         LOWLEVELCODES9, LOWLEVELCODES10, TELCODES1, TELCODES2, FAXCODE, PURCHBRWS, SALESBRWS, IMPBRWS, EXPBRWS, FINBRWS, ORGLOGOID, ADDTOREFLIST, TEXTREFTR, TEXTREFEN, ARPQUOTEINC, 
                         CLCRM, GRPFIRMNR, CONSCODEREF, SPECODE2, SPECODE3, SPECODE4, SPECODE5, OFFSENDMETHOD, OFFSENDEMAILADDR, OFFSENDFAXNR, OFFSENDFORMAT, EBANKNO, LOANGRPCTRL, BANKNAMES1, 
                         BANKNAMES2, BANKNAMES3, BANKNAMES4, BANKNAMES5, BANKNAMES6, BANKNAMES7, LDXFIRMNR, MAPID, LONGITUDE, LATITUTE, CITYID, TOWNID, BANKIBANS1, BANKIBANS2, BANKIBANS3, BANKIBANS4, 
                         BANKIBANS5, BANKIBANS6, BANKIBANS7, TCKNO, ISPERSCOMP, EXTSENDMETHOD, EXTSENDEMAILADDR, EXTSENDFAXNR, EXTSENDFORMAT, BANKBICS1, BANKBICS2, BANKBICS3, BANKBICS4, BANKBICS5, BANKBICS6, 
                         BANKBICS7, CASHREF, USEDINPERIODS, INCHARGE2, INCHARGE3, EMAILADDR2, EMAILADDR3, RSKLIMCR, RSKDUEDATECR, RSKAGINGCR, RSKAGINGDAY, ACCEPTEINV, EINVOICEID, PROFILEID, BANKBCURRENCY1, 
                         BANKBCURRENCY2, BANKBCURRENCY3, BANKBCURRENCY4, BANKBCURRENCY5, BANKBCURRENCY6, BANKBCURRENCY7, PURCORDERSTATUS, PURCORDERPRICE, ISFOREIGN, SHIPBEGTIME1, SHIPBEGTIME2, 
                         SHIPBEGTIME3, SHIPENDTIME1, SHIPENDTIME2, SHIPENDTIME3, DBSLIMIT1, DBSLIMIT2, DBSLIMIT3, DBSLIMIT4, DBSLIMIT5, DBSLIMIT6, DBSLIMIT7, DBSTOTAL1, DBSTOTAL2, DBSTOTAL3, DBSTOTAL4, DBSTOTAL5, 
                         DBSTOTAL6, DBSTOTAL7, DBSBANKNO1, DBSBANKNO2, DBSBANKNO3, DBSBANKNO4, DBSBANKNO5, DBSBANKNO6, DBSBANKNO7, DBSRISKCNTRL1, DBSRISKCNTRL2, DBSRISKCNTRL3, DBSRISKCNTRL4, 
                         DBSRISKCNTRL5, DBSRISKCNTRL6, DBSRISKCNTRL7, DBSBANKCURRENCY1, DBSBANKCURRENCY2, DBSBANKCURRENCY3, DBSBANKCURRENCY4, DBSBANKCURRENCY5, DBSBANKCURRENCY6, 
                         DBSBANKCURRENCY7, BANKCORRPACC1, BANKCORRPACC2, BANKCORRPACC3, BANKCORRPACC4, BANKCORRPACC5, BANKCORRPACC6, BANKCORRPACC7, BANKVOEN1, BANKVOEN2, BANKVOEN3, BANKVOEN4, 
                         BANKVOEN5, BANKVOEN6, BANKVOEN7, EINVOICETYPE, DEFINITION2, TELEXTNUMS1, TELEXTNUMS2, FAXEXTNUM, FACEBOOKURL, TWITTERURL, APPLEID, SKYPEID, GLOBALID, GUID, DUEDATECOUNT, DUEDATELIMIT, 
                         DUEDATETRACK, DUEDATECONTROL1, DUEDATECONTROL2, DUEDATECONTROL3, DUEDATECONTROL4, DUEDATECONTROL5, DUEDATECONTROL6, DUEDATECONTROL7, DUEDATECONTROL8, DUEDATECONTROL9, 
                         DUEDATECONTROL10, DUEDATECONTROL11, DUEDATECONTROL12, DUEDATECONTROL13, DUEDATECONTROL14, DUEDATECONTROL15, ADRESSNO, POSTLABELCODE, SENDERLABELCODE, CLOSEDATECOUNT, 
                         CLOSEDATETRACK, DEGACTIVE, DEGCURR, NAME, SURNAME, LABELINFO, DEFBNACCREF, PROJECTREF, DISCTYPE, SENDMOD, ISPERCURR, CURRATETYPE, INSTEADOFDESP, EINVOICETYP, FBSSENDMETHOD, 
                         FBSSENDEMAILADDR, FBSSENDFORMAT, FBSSENDFAXNR, FBASENDMETHOD, FBASENDEMAILADDR, FBASENDFORMAT, FBASENDFAXNR, SECTORMAINREF, SECTORSUBREF, PERSONELCOSTS, EARCEMAILADDR1, 
                         EARCEMAILADDR2, EARCEMAILADDR3, FACTORYDIVNR, FACTORYNR, ININVENNR, OUTINVENNR, QTYDEPDURATION, QTYINDEPDURATION, OVERLAPTYPE, OVERLAPAMNT, OVERLAPPERC, BROKERCOMP, 
                         CREATEWHFICHE, EINVCUSTOM, SUBCONT, ORDPRIORITY, ACCEPTEDESP, PROFILEIDDESP, LABELINFODESP, POSTLABELCODEDESP, SENDERLABELCODEDESP, ACCEPTEINVPUBLIC, PUBLICBNACCREF, 
                         PAYMENTPROCBRANCH, KVKKPERMSTATUS, KVKKBEGDATE, KVKKENDDATE, KVKKCANCELDATE, KVKKANONYSTATUS, KVKKANONYDATE, EXIMSENDMETHOD, EXIMSENDEMAILADDR, EXIMSENDFORMAT, 
                         EXIMSENDFAXNR, CLCCANDEDUCT, DRIVERREF, '' AS WFLOWCRD
FROM            dbo.LG_888_CLCARD AS LGMAIN WITH (NOLOCK)
WHERE        (CARDTYPE <> 22)